const countries = [
  { code: '+1', name: 'United States', flag: '🇺🇸' },
  { code: '+44', name: 'United Kingdom', flag: '🇬🇧' },
  { code: '+49', name: 'Germany', flag: '🇩🇪' },
  { code: '+33', name: 'France', flag: '🇫🇷' },
  { code: '+81', name: 'Japan', flag: '🇯🇵' },
  { code: '+86', name: 'China', flag: '🇨🇳' },
  { code: '+91', name: 'India', flag: '🇮🇳' },
  { code: '+55', name: 'Brazil', flag: '🇧🇷' },
  { code: '+7', name: 'Russia', flag: '🇷🇺' },
  { code: '+82', name: 'South Korea', flag: '🇰🇷' },
  { code: '+39', name: 'Italy', flag: '🇮🇹' },
  { code: '+34', name: 'Spain', flag: '🇪🇸' },
  { code: '+31', name: 'Netherlands', flag: '🇳🇱' },
  { code: '+46', name: 'Sweden', flag: '🇸🇪' },
  { code: '+47', name: 'Norway', flag: '🇳🇴' },
  { code: '+45', name: 'Denmark', flag: '🇩🇰' },
  { code: '+61', name: 'Australia', flag: '🇦🇺' },
  { code: '+64', name: 'New Zealand', flag: '🇳🇿' },
  { code: '+1', name: 'Canada', flag: '🇨🇦' },
  { code: '+52', name: 'Mexico', flag: '🇲🇽' },
  { code: '+54', name: 'Argentina', flag: '🇦🇷' },
  { code: '+56', name: 'Chile', flag: '🇨🇱' },
  { code: '+57', name: 'Colombia', flag: '🇨🇴' },
  { code: '+51', name: 'Peru', flag: '🇵🇪' },
  { code: '+90', name: 'Turkey', flag: '🇹🇷' },
  { code: '+971', name: 'UAE', flag: '🇦🇪' },
  { code: '+966', name: 'Saudi Arabia', flag: '🇸🇦' },
  { code: '+20', name: 'Egypt', flag: '🇪🇬' },
  { code: '+234', name: 'Nigeria', flag: '🇳🇬' },
  { code: '+254', name: 'Kenya', flag: '🇰🇪' },
  { code: '+27', name: 'South Africa', flag: '🇿🇦' },
  { code: '+92', name: 'Pakistan', flag: '🇵🇰' },
  { code: '+880', name: 'Bangladesh', flag: '🇧🇩' },
  { code: '+95', name: 'Myanmar', flag: '🇲🇲' },
  { code: '+66', name: 'Thailand', flag: '🇹🇭' },
  { code: '+84', name: 'Vietnam', flag: '🇻🇳' },
  { code: '+63', name: 'Philippines', flag: '🇵🇭' },
  { code: '+62', name: 'Indonesia', flag: '🇮🇩' },
  { code: '+60', name: 'Malaysia', flag: '🇲🇾' },
  { code: '+65', name: 'Singapore', flag: '🇸🇬' },
  { code: '+852', name: 'Hong Kong', flag: '🇭🇰' },
  { code: '+886', name: 'Taiwan', flag: '🇹🇼' },
  { code: '+853', name: 'Macau', flag: '🇲🇴' },
  { code: '+976', name: 'Mongolia', flag: '🇲🇳' },
  { code: '+977', name: 'Nepal', flag: '🇳🇵' },
  { code: '+975', name: 'Bhutan', flag: '🇧🇹' },
  { code: '+670', name: 'Timor-Leste', flag: '🇹🇱' },
  { code: '+678', name: 'Vanuatu', flag: '🇻🇺' },
  { code: '+679', name: 'Fiji', flag: '🇫🇯' },
  { code: '+685', name: 'Samoa', flag: '🇼🇸' },
  { code: '+690', name: 'Tokelau', flag: '🇹🇰' },
  { code: '+1670', name: 'Northern Mariana Islands', flag: '🇲🇵' },
  { code: '+1671', name: 'Guam', flag: '🇬🇺' },
  { code: '+1650', name: 'American Samoa', flag: '🇦🇸' },
  { code: '+1649', name: 'British Indian Ocean Territory', flag: '🇮🇴' },
  { code: '+246', name: 'British Virgin Islands', flag: '🇻🇬' },
  { code: '+1284', name: 'Cayman Islands', flag: '🇰🇾' },
  { code: '+1345', name: 'Cayman Islands', flag: '🇰🇾' },
  { code: '+1441', name: 'Bermuda', flag: '🇧🇲' },
  { code: '+1721', name: 'Bonaire Sint Eustatius and Saba', flag: '🇧🇶' },
  { code: '+1767', name: 'Dominica', flag: '🇩🇲' },
  { code: '+1784', name: 'Dominican Republic', flag: '🇩🇴' },
  { code: '+1809', name: 'Dominican Republic', flag: '🇩🇴' },
  { code: '+1829', name: 'Dominican Republic', flag: '🇩🇴' },
  { code: '+1849', name: 'Dominican Republic', flag: '🇩🇴' },
  { code: '+1876', name: 'Jamaica', flag: '🇯🇲' },
  { code: '+1939', name: 'Puerto Rico', flag: '🇵🇷' },
  { code: '+1940', name: 'Puerto Rico', flag: '🇵🇷' },
  { code: '+1340', name: 'US Virgin Islands', flag: '🇻🇮' },
  { code: '+1264', name: 'Anguilla', flag: '🇦🇮' },
  { code: '+1268', name: 'Antigua and Barbuda', flag: '🇦🇬' },
  { code: '+1267', name: 'Barbados', flag: '🇧🇧' },  
  { code: '+1242', name: 'Bahamas', flag: '🇧🇸' },
  { code: '+1246', name: 'Barbados', flag: '🇧🇧' },
  { code: '+1284', name: 'Cayman Islands', flag: '🇰🇾' },
  { code: '+1345', name: 'Cayman Islands', flag: '🇰🇾' },
  { code: '+1441', name: 'Bermuda', flag: '🇧🇲' },
  { code: '+1473', name: 'Grenada', flag: '🇬🇩' },
  { code: '+1571', name: 'Montserrat', flag: '🇲🇸' },
  { code: '+1584', name: 'Saint Kitts and Nevis', flag: '🇰🇳' },
  { code: '+1599', name: 'Saint Lucia', flag: '🇱🇸' },
  { code: '+1758', name: 'Saint Lucia', flag: '🇱🇸' },  
  { code: '+1784', name: 'Saint Vincent and the Grenadines', flag: '🇻🇨' },
  { code: '+1684', name: 'Saint Pierre and Miquelon', flag: '🇵🇲' },
  { code: '+1620', name: 'Saint Martin', flag: '🇫🇷' },
  { code: '+590', name: 'French Guiana', flag: '🇬🇫' },
  { code: '+594', name: 'French Guiana', flag: '🇬🇫' },  
  { code: '+596', name: 'Martinique', flag: '🇲🇶' },
  { code: '+508', name: 'Saint Pierre and Miquelon', flag: '🇵🇲' },
  { code: '+681', name: 'Wallis and Futuna', flag: '🇼🇫' },
  { code: '+689', name: 'French Polynesia', flag: '🇵🇫' },
  { code: '+687', name: 'New Caledonia', flag: '🇳🇨' },
  { code: '+672', name: 'Norfolk Island', flag: '🇳🇫' },
  { code: '+674', name: 'Nauru', flag: '🇳🇷' },
  { code: '+675', name: 'Papua New Guinea', flag: '🇵🇬' },
  { code: '+677', name: 'Solomon Islands', flag: '🇸🇧' },
  { code: '+676', name: 'Tonga', flag: '🇹🇴' },
  { code: '+688', name: 'Tuvalu', flag: '🇹🇻' },
  { code: '+680', name: 'Palau', flag: '🇵🇼' },
  { code: '+686', name: 'Kiribati', flag: '🇰🇮' },
  { code: '+692', name: 'Marshall Islands', flag: '🇲🇭' },
  { code: '+691', name: 'Micronesia', flag: '🇫🇲' },
  { code: '+683', name: 'Saint Christopher and Nevis', flag: '🇰🇳' },
  { code: '+1562', name: 'Saint Helena', flag: '🇸🇭' },
  { code: '+1352', name: 'Falkland Islands', flag: '🇫🇰' },
  { code: '+500', name: 'Falkland Islands', flag: '🇫🇰' },
  { code: '+44', name: 'Isle of Man', flag: '🇮🇲' },
  { code: '+1534', name: 'Jersey', flag: '🇯🇪' },
  { code: '+350', name: 'Gibraltar', flag: '🇬🇮' },
  { code: '+298', name: 'Faroe Islands', flag: '🇫🇴' },
  { code: '+299', name: 'Greenland', flag: '🇬🇱' },
  { code: '+1681', name: 'Aldra', flag: '🇦🇱' },
  { code: '+376', name: 'Andorra', flag: '🇦🇩' },
  { code: '+43', name: 'Austria', flag: '🇦🇹' },
  { code: '+375', name: 'Belarus', flag: '🇧🇾' },
  { code: '+32', name: 'Belgium', flag: '🇧🇪' },
  { code: '+387', name: 'Bosnia and Herzegovina', flag: '🇧🇦' },
  { code: '+359', name: 'Bulgaria', flag: '🇧🇬' },
  { code: '+385', name: 'Croatia', flag: '🇭🇷' },
  { code: '+357', name: 'Cyprus', flag: '🇨🇾' },
  { code: '+420', name: 'Czech Republic', flag: '🇨🇿' },
  { code: '+45', name: 'Faroe Islands', flag: '🇫🇴' },
  { code: '+372', name: 'Estonia', flag: '🇪🇪' },
  { code: '+358', name: 'Finland', flag: '🇫🇮' },
  { code: '+995', name: 'Georgia', flag: '🇬🇪' },
  { code: '+350', name: 'Gibraltar', flag: '🇬🇮' },  
  { code: '+336', name: 'France', flag: '🇫🇷' },
  { code: '+337', name: 'France', flag: '🇫🇷' },
  { code: '+49', name: 'Germany', flag: '🇩🇪' },
  { code: '+30', name: 'Greece', flag: '🇬🇷' },
  { code: '+36', name: 'Hungary', flag: '🇭🇺' },
  { code: '+354', name: 'Iceland', flag: '🇮🇸' },
  { code: '+353', name: 'Ireland', flag: '🇮🇪' },
  { code: '+383', name: 'Kosovo', flag: '🇽🇰' },
  { code: '+371', name: 'Latvia', flag: '🇱🇻' },
  { code: '+370', name: 'Lithuania', flag: '🇱🇹' },
  { code: '+356', name: 'Malta', flag: '🇲🇹' },
  { code: '+373', name: 'Moldova', flag: '🇲🇩' },
  { code: '+377', name: 'Monaco', flag: '🇲🇨' },
  { code: '+382', name: 'Montenegro', flag: '🇲🇪' },
  { code: '+212', name: 'Morocco', flag: '🇲🇦' },
  { code: '+377', name: 'Monaco', flag: '🇲🇨' },  
  { code: '+31', name: 'Netherlands', flag: '🇳🇱' },
  { code: '+47', name: 'Norway', flag: '🇳🇴' },
  { code: '+48', name: 'Poland', flag: '🇵🇱' },
  { code: '+351', name: 'Portugal', flag: '🇵🇹' },
  { code: '+40', name: 'Romania', flag: '🇷🇴' },
  { code: '+378', name: 'San Marino', flag: '🇸🇲' },
  { code: '+381', name: 'Serbia', flag: '🇷🇸' },
  { code: '+421', name: 'Slovakia', flag: '🇸🇰' },
  { code: '+386', name: 'Slovenia', flag: '🇸🇮' },
  { code: '+34', name: 'Spain', flag: '🇪🇸' },
  { code: '+41', name: 'Switzerland', flag: '🇨🇭' },
  { code: '+380', name: 'Ukraine', flag: '🇺🇦' },
  { code: '+44', name: 'United Kingdom', flag: '🇬🇧' },
  { code: '+216', name: 'Tunisia', flag: '🇹🇳' },
  { code: '+962', name: 'Jordan', flag: '🇯🇴' },
  { code: '+963', name: 'Syria', flag: '🇸🇾' },
  { code: '+964', name: 'Iraq', flag: '🇮🇶' },
  { code: '+965', name: 'Kuwait', flag: '🇰🇼' },
  { code: '+968', name: 'Oman', flag: '🇴🇲' },
  { code: '+970', name: 'Palestine', flag: '🇵🇸' },
  { code: '+973', name: 'Bahrain', flag: '🇧🇭' },
  { code: '+212', name: 'Morocco', flag: '🇲🇦' },
  { code: '+216', name: 'Tunisia', flag: '🇹🇳' },  
  { code: '+218', name: 'Libya', flag: '🇱🇾' },
  { code: '+222', name: 'Mauritania', flag: '🇲🇱' },
  { code: '+223', name: 'Mali', flag: '🇲🇱' },
  { code: '+224', name: 'Guinea', flag: '🇬🇳' },
  { code: '+225', name: "Cote d'Ivoire", flag: '🇨🇮' },
  { code: '+226', name: 'Burkina Faso', flag: '🇧🇫' },
  { code: '+227', name: 'Niger', flag: '🇳🇪' },
  { code: '+228', name: 'Togo', flag: '🇹🇬' },
  { code: '+229', name: 'Benin', flag: '🇧🇯' },
  { code: '+230', name: 'Mauritius', flag: '🇲🇺' },
  { code: '+231', name: 'Liberia', flag: '🇱🇷' },
  { code: '+232', name: 'Sierra Leone', flag: '🇸🇱' },
  { code: '+233', name: 'Ghana', flag: '🇬🇭' },
  { code: '+235', name: 'Chad', flag: '🇹🇩' },
  { code: '+236', name: 'Central African Republic', flag: '🇨🇫' },
  { code: '+237', name: 'Cameroon', flag: '🇨🇲' },
  { code: '+238', name: 'Cape Verde', flag: '🇨🇻' },
  { code: '+239', name: 'Sao Tome and Principe', flag: '🇸🇹' },
  { code: '+240', name: 'Equatorial Guinea', flag: '🇬🇶' },
  { code: '+241', name: 'Gabon', flag: '🇬🇦' },
  { code: '+242', name: 'Republic of the Congo', flag: '🇨🇬' },
  { code: '+243', name: 'Democratic Republic of the Congo', flag: '🇨🇩' },
  { code: '+244', name: 'Angola', flag: '🇦🇴' },
  { code: '+245', name: 'Guinea-Bissau', flag: '🇬🇼' },
  { code: '+246', name: 'British Indian Ocean Territory', flag: '🇮🇴' },  
  { code: '+248', name: 'Seychelles', flag: '🇸🇨' },
  { code: '+249', name: 'Sudan', flag: '🇸🇩' },
  { code: '+250', name: 'Rwanda', flag: '🇷🇼' },
  { code: '+251', name: 'Ethiopia', flag: '🇪🇹' },
  { code: '+252', name: 'Somalia', flag: '🇸🇴' },
  { code: '+253', name: 'Djibouti', flag: '🇩🇯' },
  { code: '+255', name: 'Tanzania', flag: '🇹🇿' },
  { code: '+256', name: 'Uganda', flag: '🇺🇬' },
  { code: '+257', name: 'Burundi', flag: '🇧🇮' },
  { code: '+258', name: 'Mozambique', flag: '🇲🇿' },
  { code: '+260', name: 'Zambia', flag: '🇿🇲' },
  { code: '+263', name: 'Zimbabwe', flag: '🇿🇼' },
  { code: '+264', name: 'Namibia', flag: '🇳🇦' },
  { code: '+265', name: 'Malawi', flag: '🇲🇼' },
  { code: '+266', name: 'Lesotho', flag: '🇱🇸' },
  { code: '+267', name: 'Botswana', flag: '🇧🇼' },
  { code: '+268', name: 'Swaziland', flag: '🇸🇿' },
  { code: '+269', name: 'Comoros', flag: '🇰🇲' },
  { code: '+290', name: 'Saint Helena', flag: '🇸🇭' },
  { code: '+291', name: 'Eritrea', flag: '🇪🇷' },
  { code: '+297', name: 'Aruba', flag: '🇦🇼' },  
  { code: '+298', name: 'Faroe Islands', flag: '🇫🇴' },
  { code: '+299', name: 'Greenland', flag: '🇬🇱' },  
  { code: '+500', name: 'Falkland Islands', flag: '🇫🇰' },
  { code: '+501', name: 'Belize', flag: '🇧🇿' },
  { code: '+502', name: 'Guatemala', flag: '🇬🇹' },
  { code: '+503', name: 'El Salvador', flag: '🇸🇻' },
  { code: '+504', name: 'Honduras', flag: '🇭🇳' },
  { code: '+505', name: 'Nicaragua', flag: '🇳🇮' },
  { code: '+506', name: 'Costa Rica', flag: '🇨🇷' },
  { code: '+507', name: 'Panama', flag: '🇵🇦' },
  { code: '+508', name: 'Saint Pierre and Miquelon', flag: '🇵🇲' },
  { code: '+509', name: 'Haiti', flag: '🇭🇹' },
  { code: '+521', name: 'Mexico', flag: '🇲🇽' },
  { code: '+535', name: 'Cuba', flag: '🇨🇺' },
  { code: '+539', name: 'Cuba', flag: '🇨🇺' },
  { code: '+542', name: 'Argentina', flag: '🇦🇷' },
  { code: '+543', name: 'Argentina', flag: '🇦🇷' },
  { code: '+544', name: 'Argentina', flag: '🇦🇷' },
  { code: '+545', name: 'Argentina', flag: '🇦🇷' },
  { code: '+546', name: 'Argentina', flag: '🇦🇷' },
  { code: '+547', name: 'Peru', flag: '🇵🇪' },
  { code: '+548', name: 'Colombia', flag: '🇨🇴' },
  { code: '+549', name: 'Argentina', flag: '🇦🇷' },
  { code: '+551', name: 'Brazil', flag: '🇧🇷' },
  { code: '+552', name: 'Brazil', flag: '🇧🇷' },
  { code: '+553', name: 'Brazil', flag: '🇧🇷' },
  { code: '+554', name: 'Brazil', flag: '🇧🇷' },
  { code: '+555', name: 'Brazil', flag: '🇧🇷' },
  { code: '+556', name: 'Brazil', flag: '🇧🇷' },
  { code: '+557', name: 'Brazil', flag: '🇧🇷' },
  { code: '+558', name: 'Brazil', flag: '🇧🇷' }],
  default: '+1'
};
module.exports = countries;