apiVersion: v1
kind: Namespace
metadata:
  name: tigerex
  labels:
    name: tigerex
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: tigerex-monitoring
  labels:
    name: tigerex-monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: tigerex-staging
  labels:
    name: tigerex-staging